### ISSUE TITLE
Won't run on Ubuntu

### ISSUE THREAD

**Issue by psiphi75** [itadinanta/rust-oids#11]
I've compiled the code using stable Rust v1.40.0. There were no build errors or warnings. I followed the instructions for Ubuntu dependencies, but when I run `RUST_BACKTRACE=full cargo run --release` I get the following run-time error.  I'm running on Ubuntu 19.10 using Gnome Wayland.

```text
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55bac9e462c4 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55bac9e462c4 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55bac9e462c4 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55bac9e462c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55bac9e678cc - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55bac9e43547 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55bac9e4884e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55bac9e4884e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55bac9e4884e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55bac9e48541 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55bac9e48f4b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55bac9e48aee - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x55bac9e489d6 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x55bac9e6393e - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x55bac9e63a37 - core::result::unwrap_failed::h054dd680e6fcd38b
                               at src/libcore/result.rs:1165
  15:     0x55bac9cb5426 - rust_oids::app::main::main_loop::h5aea3fc977547547
  16:     0x55bac9c5a0f8 - rust_oids::app::run::hbb5e1390a2ec2f18
  17:     0x55bac9c896ff - rust_oids::main::h31f8fa382cd0227f
  18:     0x55bac9ca4f53 - std::rt::lang_start::{{closure}}::hbea537056d035c7a
  19:     0x55bac9e48973 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  20:     0x55bac9e48973 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  21:     0x55bac9e4cd8a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  22:     0x55bac9e494ed - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  23:     0x55bac9e494ed - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  24:     0x55bac9e494ed - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  25:     0x55bac9c8a302 - main
  26:     0x7f06a06ac1e3 - __libc_start_main
  27:     0x55bac9bdf33e - _start
  28:                0x0 - <unknown>
```

**Comment by norru** [comment]
Tried to repro on Devuan (Debian based), cannot reproduce.

Will try Ubuntu ASAP.

**Comment by norru** [comment]
I never tested on Wayland though.

**Comment by norru** [comment]
Tried on Ubuntu 18.04, XFCE. Can't repro.
